//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAP.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class FileInfo
    {
        public FileInfo()
        {
            this.DelFlag = 0;
        }
    
        public int Id { get; set; }
        public string FileName { get; set; }
        public string FileType { get; set; }
        public string FilePath { get; set; }
        public string FileSize { get; set; }
        public string Remark { get; set; }
        public System.DateTime SubTime { get; set; }
        public short DelFlag { get; set; }
        public Nullable<int> WF_InstanceId { get; set; }
    
        public virtual WF_Instance WF_Instance { get; set; }
    }
}
