//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAP.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class UserInfo
    {
        public UserInfo()
        {
            this.DelFlag = 0;
            this.OrderInfo = new HashSet<OrderInfo>();
            this.RoleInfo = new HashSet<RoleInfo>();
            this.R_UserInfo_ActionInfo = new HashSet<R_UserInfo_ActionInfo>();
        }
    
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string Password { get; set; }
        public string UserName { get; set; }
        public string LastName { get; set; }
        public string Remark { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public System.DateTime SubTime { get; set; }
        public short DelFlag { get; set; }
    
        public virtual ICollection<OrderInfo> OrderInfo { get; set; }
        public virtual ICollection<RoleInfo> RoleInfo { get; set; }
        public virtual ICollection<R_UserInfo_ActionInfo> R_UserInfo_ActionInfo { get; set; }
    }
}
