//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAP.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class WF_Instance
    {
        public WF_Instance()
        {
            this.DelFlag = 0;
            this.FileInfo = new HashSet<FileInfo>();
            this.WF_Procedure = new HashSet<WF_Procedure>();
        }
    
        public int Id { get; set; }
        public string InstanceName { get; set; }
        public int SenderId { get; set; }
        public System.DateTime StartTime { get; set; }
        public short Level { get; set; }
        public string Content { get; set; }
        public string Remark { get; set; }
        public short DelFlag { get; set; }
        public string FilePath { get; set; }
        public System.Guid WFInstanceId { get; set; }
        public int WF_TempId { get; set; }
        public short Status { get; set; }
    
        public virtual ICollection<FileInfo> FileInfo { get; set; }
        public virtual WF_Temp WF_Temp { get; set; }
        public virtual ICollection<WF_Procedure> WF_Procedure { get; set; }
    }
}
