//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAP.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class WF_Procedure
    {
        public int Id { get; set; }
        public string ProcedureName { get; set; }
        public int HandleBy { get; set; }
        public System.DateTime SubTime { get; set; }
        public System.DateTime ProcessTime { get; set; }
        public string ProcessResult { get; set; }
        public string ProcessComment { get; set; }
        public short ProcessStatus { get; set; }
        public bool IsStartProcedure { get; set; }
        public bool IsEndProcedure { get; set; }
        public string ParentProcedureId { get; set; }
        public int WF_InstanceId { get; set; }
    
        public virtual WF_Instance WF_Instance { get; set; }
    }
}
