//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAP.OA.Model
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public partial class WF_Temp
    {
        public WF_Temp()
        {
            this.DelFlag = 0;
            this.WF_Instance = new HashSet<WF_Instance>();
        }
    
        public int Id { get; set; }
        public string TempName { get; set; }
        public string Decription { get; set; }
        public string TempForm { get; set; }
        public string Remark { get; set; }
        public System.DateTime SubTime { get; set; }
        public short DelFlag { get; set; }
        public string ActivityType { get; set; }
    
        public virtual ICollection<WF_Instance> WF_Instance { get; set; }
    }
}
